apiVersion: v1
kind: ServiceAccount
metadata:
  name: checkout-sa
  namespace: payments
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: checkout
  namespace: payments
  labels:
    app: checkout
spec:
  replicas: 1
  selector:
    matchLabels:
      app: checkout
  template:
    metadata:
      labels:
        app: checkout
    spec:
      serviceAccountName: checkout-sa
      containers:
      - name: checkout
        image: anshumaan10/checkout:a8bb30c7ae57cf7d0b01135a9ffade2108fa2930
        env:
        - name: PAYMENT_API_URL
          value: "http://payment-api:8080/transactions"
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "200m"
        securityContext:
          runAsNonRoot: true
          runAsUser: 1000
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
        volumeMounts:
        - name: tmp
          mountPath: /tmp
      volumes:
      - name: tmp
        emptyDir: {}
      imagePullSecrets:
      - name: dockerhub-secret
